---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-06-12 6:27 PM
---

--[[
Command line utility to compile list of .lua files to .obj format (using luajit -b)
and then bundle all files to a static library to be linked with C/C++ project
]]

local os = require 'os'
local path = require 'pl.path'
local lapp = require 'pl.lapp'

local cli_args = lapp [[
Compile lua-to-static-library
<filelist> (string)  Path to file list .lua module
    -n, --name (string default 'luaModules.a')  Name of target library
    -o, --output (string default 'obj_lua')  Output path
]]

local file_list = path.abspath(path.relpath(cli_args.filelist))

--local files = require(cli_args.filelist)
local files = loadfile(file_list)()

local libName = path.splitext(path.basename(cli_args.name))

local out_path = path.join(path.abspath(path.relpath(cli_args.output)), libName)
os.execute(string.format('mkdir -p "%s"', out_path))

for file_name, module_name in pairs(files) do
    -- Compile .lua file
    local nn = ''
    if type(file_name) ~= 'number'
            and type(module_name) == 'string' and module_name ~= '' then
        nn = 'n ' .. module_name
    else
        file_name = module_name
    end

    print(string.format('Compiling %s...', file_name))

    -- Current directory is expected to be flexilite
    local file_path = path.abspath(path.relpath(file_name))

    local o_file = string.gsub(file_name, '/', '.')
    local cmd = string.format('luajit -b%s "%s" "%s"',
            nn, file_path, path.join(out_path, o_file .. '.o'))

    print(os.execute(cmd))
end

-- Bundle library into single archive
local cmd = string.format('ar rcus %s %s/*.o', path.join(out_path, cli_args.name), out_path)
print(cmd)
print(os.execute(cmd))

