---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-08-26 10:36 AM
---

--[[ This file is used for debugging flexish CLI in LuaJIT interpreter.
This script embeds index.lua (which is normal starting point used
in the compiled EXE), and registers paths in ./lib folder for all Lua dependencies
  ]]



require 'index'