---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-06-12 6:25 PM
---

return {
    -- flexish
    ['classCreate.lua'] = 'classCreate',
    ['dumpDatabase.lua'] = 'dumpDatabase',
    ['getStat.lua'] = 'getStat',
    ['index.lua'] = 'index',
    ['initDb.lua'] = 'initDb',
    ['runQuery.lua'] = 'runQuery',
    ['sqliteSchemaParser.lua'] = 'sqliteSchemaParser',

    -- misc libs
    ['../lib/lua-prettycjson/lib/resty/prettycjson.lua'] = 'prettycjson',
    ['../lib/lua-ansicolors/ansicolors.lua'] = 'ansicolors',

    -- penlight
    ['../lib/lua-penlight/lua/pl/Date.lua'] = 'pl.Date',
    ['../lib/lua-penlight/lua/pl/Set.lua'] = 'pl.Set',
    ['../lib/lua-penlight/lua/pl/comprehension.lua'] = 'pl.comprehension',
    ['../lib/lua-penlight/lua/pl/func.lua'] = 'pl.func',
    ['../lib/lua-penlight/lua/pl/lexer.lua'] = 'pl.lexer',
    ['../lib/lua-penlight/lua/pl/pretty.lua'] = 'pl.pretty',
    ['../lib/lua-penlight/lua/pl/stringx.lua'] = 'pl.stringx',
    ['../lib/lua-penlight/lua/pl/types.lua'] = 'pl.types',
    ['../lib/lua-penlight/lua/pl/List.lua'] = 'pl.List',
    ['../lib/lua-penlight/lua/pl/app.lua'] = 'pl.app',
    ['../lib/lua-penlight/lua/pl/config.lua'] = 'pl.config',
    ['../lib/lua-penlight/lua/pl/import_into.lua'] = 'pl.import_into',
    ['../lib/lua-penlight/lua/pl/luabalanced.lua'] = 'pl.luabalanced',
    ['../lib/lua-penlight/lua/pl/seq.lua'] = 'pl.seq',
    ['../lib/lua-penlight/lua/pl/tablex.lua'] = 'pl.tablex',
    ['../lib/lua-penlight/lua/pl/url.lua'] = 'pl.url',
    ['../lib/lua-penlight/lua/pl/Map.lua'] = 'pl.Map',
    ['../lib/lua-penlight/lua/pl/array2d.lua'] = 'pl.array2d',
    ['../lib/lua-penlight/lua/pl/data.lua'] = 'pl.data',
    ['../lib/lua-penlight/lua/pl/init.lua'] = 'pl.init',
    ['../lib/lua-penlight/lua/pl/operator.lua'] = 'pl.operator',
    ['../lib/lua-penlight/lua/pl/sip.lua'] = 'pl.sip',
    ['../lib/lua-penlight/lua/pl/template.lua'] = 'pl.template',
    ['../lib/lua-penlight/lua/pl/utils.lua'] = 'pl.utils',
    ['../lib/lua-penlight/lua/pl/MultiMap.lua'] = 'pl.MultiMap',
    ['../lib/lua-penlight/lua/pl/class.lua'] = 'pl.class',
    ['../lib/lua-penlight/lua/pl/dir.lua'] = 'pl.dir',
    ['../lib/lua-penlight/lua/pl/input.lua'] = 'pl.input',
    ['../lib/lua-penlight/lua/pl/path.lua'] = 'pl.path',
    ['../lib/lua-penlight/lua/pl/strict.lua'] = 'pl.strict',
    ['../lib/lua-penlight/lua/pl/test.lua'] = 'pl.test',
    ['../lib/lua-penlight/lua/pl/xml.lua'] = 'pl.xml',
    ['../lib/lua-penlight/lua/pl/OrderedMap.lua'] = 'pl.OrderedMap',
    ['../lib/lua-penlight/lua/pl/compat.lua'] = 'pl.compat',
    ['../lib/lua-penlight/lua/pl/file.lua'] = 'pl.file',
    ['../lib/lua-penlight/lua/pl/lapp.lua'] = 'pl.lapp',
    ['../lib/lua-penlight/lua/pl/permute.lua'] = 'pl.permute',
    ['../lib/lua-penlight/lua/pl/stringio.lua'] = 'pl.stringio',
    ['../lib/lua-penlight/lua/pl/text.lua'] = 'pl.text',
 }
