---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-08-06 3:32 PM
---

--[[
parse schema Northwind
parse schema Chinook
dump data
use external configuration
load data
]]