---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-01-21 12:36 PM
---

describe('alter property tests', function()

    pending('dummy',
       function()

       end)
end)