---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-01-21 12:36 PM
---

describe('alter property tests', function()

    pending('rename',
            function()

            end)
end)