---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-07-16 8:20 AM
---

local util = require 'util'
local path = require 'pl.path'

describe('SQLite extensions: Flexilite EAV', function()
    ---@type DBContext
    local db

    setup(function()
        db = util.openFlexiDatabase('test_ttc.db')
    end);

    teardown(function()
        if db then
            db:close()
        end
    end)

    pending('import Northwind to memory', function()
    end)

    ---@param tableName string
    local function importTable(tableName)

    end

    pending('import TTC.trips', function()
        importTable('trips')

    end)

    pending('import TTC.agency', function()
        importTable('agency')
    end)

    pending('import TTC.calendar', function()
        importTable('calendar')
    end)

    pending('import TTC.calendar_dates', function()
        importTable('calendar_dates')
    end)

    pending('import TTC.routes', function()
        importTable('routes')

    end)

    pending('import TTC.shapes', function()
        importTable('shapes')

    end)

    pending('import TTC.stop_times', function()
        importTable('stop_times')

    end)

    pending('get trip count', function()

    end)

end)


