---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-01-21 12:37 PM
---

local os = require 'os'
local util = require 'test_util'
local path = require 'pl.path'

describe('Loading entire database from JSON and verifies accuracy of imported data', function()

    setup(function()
        local dbChinookPath = path.abspath(path.relpath('../data/Chinook-flexi.db3'))
        os.remove(dbChinookPath)

        local dbChinook = util.openFlexiDatabase(dbChinookPath)
        print('Chinook: opened')

        --local dbChinook = util.openFlexiDatabaseInMem()
        util.createChinookSchema(dbChinook)
        print('Chinook: schema created')

        util.importChinookData(dbChinook)
        print('Chinook: data imported')

        local dbNorthwindPath = path.abspath(path.relpath('../data/Northwind-flexi.db3'))
        os.remove(dbNorthwindPath)

        --local dbNorthwind = util.openFlexiDatabaseInMem()
        local dbNorthwind = util.openFlexiDatabase(dbNorthwindPath)
        print('Northwind: opened')

        util.createNorthwindSchema(dbNorthwind)
        print('Northwind: schema created')

        util.importNorthwindData(dbNorthwind)
        print('Northwind: data imported')

    end)

    it('verify Northwind', function()

    end)

    it('verify Chinook', function()

    end)

    it('SqliteTable:_appendWhere: updatable view', function()
    end)

    it('SqliteTable:_appendWhere: table with one column primary key', function()
    end)

    it('SqliteTable:_appendWhere: table with multi primary key', function()
    end)

    it('SqliteTable:_appendWhere: table with single column primary key', function()
    end)

    it('SqliteTable:_appendWhere: string where', function()
    end)


end)
