---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-01-21 12:37 PM
---

local util = require('util')

describe('Loading entire database from JSON and verifies accuracy of imported data', function()

    setup(function()
        --local dbChinook = util.openFlexiDatabase('/Users/ruslanskorynin/Documents/Github/slanska/flexilite/data/Chinook-flexi.db3')
        local dbChinook = util.openFlexiDatabaseInMem()
        util.createChinookSchema(dbChinook)
        util.importChinookData(dbChinook)

        local dbNorthwind = util.openFlexiDatabaseInMem()
        --local dbNorthwind = util.openFlexiDatabase('/Users/ruslanskorynin/Documents/Github/slanska/flexilite/data/Northwind-flexi.db3')
        util.createNorthwindSchema(dbNorthwind)
        util.importNorthwindData(dbNorthwind)
    end)

    it('verify Northwind', function()

    end)

    it('verify Chinook', function()

    end)
end)