---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-07-17 12:54 PM
---


describe('Typical scenarios of data refactoring', function()
    pending('1. Create', function()

    end)

    pending('2. Name -> FirstName + LastName', function()
    end)

    pending('3. Add Email and Phone', function()
    end)

    pending('4. Extract Address into separate entity', function()
    end)

    pending('5. Multiple emails and phones', function()
    end)

    pending('6. Multiple addresses', function()
    end)

end)