---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-04-15 11:00 PM
---

--[[ Busted tests for property value access and operations]]

local class = require 'pl.class'

---@class DummyDBOV
---@field ID number
---@field ClassDef ClassDef

local ProductClassDef = require 'test_class_def'
local DBProperty = require 'DBProperty'

local DummyDBOV = class()

function DummyDBOV:_init(ClassDef, ID)
    self.ClassDef = ClassDef
    self.ID = ID
end

describe('Property Ops', function()

    it('QuantityPerUnit + 10', function()

    end)

    it('QuantityPerUnit * UnitPrice', function()

    end)
end)