---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-04-15 11:00 PM
---

--[[ Busted tests for property value access and operations]]

local pretty = require 'pl.pretty'

local test_util = require 'util'
local DBQuery = require('QueryBuilder').DBQuery

-- In memory database
---@type DBContext
local DBContext = test_util.openFlexiDatabaseInMem()
test_util.createNorthwindSchema(DBContext)
test_util.importNorthwindData(DBContext)

--local ProductClassDef = require 'test_class_def'
--local DBProperty = require 'DBProperty'

describe('Property Ops:', function()
    ---@type ClassDef
    local productsClassDef = assert(DBContext:getClassDef('Products'))
    --pretty.dump(DBContext, './DBContext.dump')

    it('QuantityPerUnit + 10', function()

    end)

    it('QuantityPerUnit * UnitPrice', function()

    end)

    it('UnitPrice > 11 and UnitPrice < 21.1', function()
        local qry = DBQuery(productsClassDef, 'UnitPrice > 11 and UnitPrice < 21.1')
        local found = qry:Run()
        print('#qry.ObjectIDs:', #qry.ObjectIDs)
    end)
end)