---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-07-16 8:15 AM
---

describe('Advanced cases of data refactoring', function()
    it('1. Merge objects', function()
    end)

    it('2. Split objects', function()
    end)

    it('3. Change class type (assign objects to a different class)', function()
    end)

    it('4. Rename class', function()
    end)

    it('5. Rename property', function()
    end)

    it('6. One-to-many -> many-to-many', function()
    end)

    --[[
    Country text column -> Extract to separate object, replace with country ID -> include into row
    by auto-generated link to Countries
    ]]
    it('7. Scalar value(s) -> Extract to separate object -> Display value(s) from referenced object', function()
    end)
end)