---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-04-16 7:02 PM
---

local util = require 'util'
local path = require 'pl.path'
local CreateClass = require('flexi_CreateClass').CreateClass

---@param DBContext DBContext
---@return ClassDef
local function createProductsClass(DBContext)
    local __dirname = path.abspath('..')
    local schemaFile = path.join(__dirname, 'test', 'json', 'Northwind.Products.schema.json')
    local schema = util.readAll(schemaFile)

    CreateClass(DBContext, 'Product', schema, false)
    local classDef = DBContext:getClassDef('Product')
    return classDef
end

local DBContext = util.openFlexiDatabaseInMem()
local ProductClassDef = createProductsClass(DBContext)

return ProductClassDef