---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-10-14 11:37 AM
---

local class = require 'pl.class'

---@class ClassStorage
local ClassStorage = class()

---@class RefValueClassStorage
local RefValueClassStorage = class()

return {
    ClassStorage = ClassStorage,
    RefValueClassStorage = RefValueClassStorage,
}

