---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-05-29 7:16 PM
---

--[[
Provides API for processing column mapping.
Column mapping is intended for faster and more compact storage and
is applicable to all scalar properties (including enum)
with maxOccurrences = 1  and
(for string and binary properties) with maxLength <= 255.

]]

local function ColMapping()

end

return ColMapping