---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-01-12 5:37 PM
---

--[[
DBProperty and derived classes.
Used by DBObject to access object property values
Instantiated by PropertyDef and its descendants
]]

local class = require 'pl.class'

---@class BaseDBProperty
local BaseDBProperty = class()

---@param DBObject DBObject
---@param propDef PropertyDef
function BaseDBProperty:_init(DBObject, propDef)
    self.DBObject = assert(DBObject)
    self.PropDef = assert(propDef)
end

function BaseDBProperty:Boxed()

end

---@class DBProperty
local DBProperty = class(BaseDBProperty)

function DBProperty:_init(DBObject, propDef)
    self:super(DBObject, propDef)
end

---@class MixinDBProperty
local MixinDBProperty = class(BaseDBProperty)

function MixinDBProperty:_init(DBObject, propDef)
    self:super(DBObject, propDef)
end
---@class LinkDBProperty
local LinkDBProperty = class(MixinDBProperty)

function LinkDBProperty:_init(DBObject, propDef)
    self:super(DBObject, propDef)
end

return {
    DBProperty = DBProperty,
    MixinDBProperty = MixinDBProperty,
    LinkDBProperty = LinkDBProperty
}