---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-06-12 6:25 PM
---

--[[
List of all Lua files (including 3rd parties) with paths relative to the project
Optional value is an alternative module name, to be used when compiling .lua
to .obj, to avoid name clash
]]

return {
    --src_lua/
    ['src_lua/NameRef.lua'] = 'NameRef',
    ['src_lua/UserInfo.lua'] = 'UserInfo',
    ['src_lua/flexi_CreateClass.lua'] = 'flexi_CreateClass',
    'src_lua/flexi_DropClass.lua',
    'src_lua/flexi_SplitProperty.lua',
    'src_lua/ClassDef.lua',
    'src_lua/flexi_AlterClass.lua',
    'src_lua/flexi_CreateProperty.lua',
    'src_lua/flexi_DropProperty.lua',
    'src_lua/flexi_StructuralMerge.lua',
    'src_lua/DBContext.lua',
    'src_lua/PropertyDef.lua',
    'src_lua/flexi_AlterProperty.lua',
    'src_lua/flexi_DataBestIndex.lua',
    'src_lua/flexi_MergeProperty.lua',
    'src_lua/flexi_StructuralSplit.lua',
    'src_lua/EnumManager.lua',
    'src_lua/QueryBuilder.lua',
    'src_lua/flexi_Configure.lua',
    'src_lua/flexi_DataFilter.lua',
    'src_lua/flexi_ObjectToProp.lua',
    'src_lua/index.lua',
    'src_lua/JulianDate.lua',
    'src_lua/Triggers.lua',
    'src_lua/flexi_ConvertCustomEAV.lua',
    'src_lua/flexi_DataUpdate.lua',
    'src_lua/flexi_PropToObject.lua',
    'src_lua/DBObject.lua',
    'src_lua/Constants.lua',
    'src_lua/AccessControl.lua',
    'src_lua/Util.lua',
    'src_lua/DBValue.lua',
    'src_lua/ApiGlobalObject.lua',
    'src_lua/ApiGlobalScope.lua',
    'src_lua/DBProperty.lua',
    'src_lua/ColMapping.lua',

    -- lib
    'lib/lua-prettycjson/lib/resty/prettycjson.lua',
    'lib/lua-schema/schema.lua',

    -- penlight
    'lib/lua-penlight/lua/pl/Date.lua',
    'lib/lua-penlight/lua/pl/Set.lua',
    'lib/lua-penlight/lua/pl/comprehension.lua',
    'lib/lua-penlight/lua/pl/func.lua',
    ['lib/lua-penlight/lua/pl/lexer.lua'] = 'pl.lexer',
    'lib/lua-penlight/lua/pl/pretty.lua',
    'lib/lua-penlight/lua/pl/stringx.lua',
    'lib/lua-penlight/lua/pl/types.lua',
    'lib/lua-penlight/lua/pl/List.lua',
    'lib/lua-penlight/lua/pl/app.lua',
    'lib/lua-penlight/lua/pl/config.lua',
    'lib/lua-penlight/lua/pl/import_into.lua',
    'lib/lua-penlight/lua/pl/luabalanced.lua',
    'lib/lua-penlight/lua/pl/seq.lua',
    'lib/lua-penlight/lua/pl/tablex.lua',
    'lib/lua-penlight/lua/pl/url.lua',
    'lib/lua-penlight/lua/pl/Map.lua',
    'lib/lua-penlight/lua/pl/array2d.lua',
    'lib/lua-penlight/lua/pl/data.lua',
    'lib/lua-penlight/lua/pl/init.lua',
    'lib/lua-penlight/lua/pl/operator.lua',
    'lib/lua-penlight/lua/pl/sip.lua',
    'lib/lua-penlight/lua/pl/template.lua',
    'lib/lua-penlight/lua/pl/utils.lua',
    'lib/lua-penlight/lua/pl/MultiMap.lua',
    'lib/lua-penlight/lua/pl/class.lua',
    'lib/lua-penlight/lua/pl/dir.lua',
    'lib/lua-penlight/lua/pl/input.lua',
    'lib/lua-penlight/lua/pl/path.lua',
    'lib/lua-penlight/lua/pl/strict.lua',
    'lib/lua-penlight/lua/pl/test.lua',
    'lib/lua-penlight/lua/pl/xml.lua',
    'lib/lua-penlight/lua/pl/OrderedMap.lua',
    'lib/lua-penlight/lua/pl/compat.lua',
    'lib/lua-penlight/lua/pl/file.lua',
    'lib/lua-penlight/lua/pl/lapp.lua',
    'lib/lua-penlight/lua/pl/permute.lua',
    'lib/lua-penlight/lua/pl/stringio.lua',
    'lib/lua-penlight/lua/pl/text.lua',

    -- sandbox
    'lib/lua-sandbox/sandbox.lua',

    -- metalua-parser
    ['lib/lua-metalua/metalua/grammar/generator.lua'] = 'metalua.grammar.generator',
    ['lib/lua-metalua/metalua/grammar/lexer.lua'] = 'metalua.grammar.lexer',
    'lib/lua-metalua/metalua/compiler/parser.lua',
    'lib/lua-metalua/metalua/compiler/parser/common.lua',
    'lib/lua-metalua/metalua/compiler/parser/table.lua',
    'lib/lua-metalua/metalua/compiler/parser/ext.lua',
    ['lib/lua-metalua/metalua/compiler/parser/annot/generator.lua'] = 'metalua.compiler.parser.annot.generator',
    'lib/lua-metalua/metalua/compiler/parser/annot/grammar.lua',
    'lib/lua-metalua/metalua/compiler/parser/stat.lua',
    'lib/lua-metalua/metalua/compiler/parser/misc.lua',
    ['lib/lua-metalua/metalua/compiler/parser/lexer.lua'] = 'metalua.compiler.parser.lexer',
    'lib/lua-metalua/metalua/compiler/parser/meta.lua',
    'lib/lua-metalua/metalua/compiler/parser/expr.lua',
    'lib/lua-metalua/metalua/compiler.lua',
    'lib/lua-metalua/metalua/pprint.lua',
}