---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-06-12 6:25 PM
---

--[[
List of all Lua files (including 3rd parties) with paths relative to the project
Optional value is an alternative module name, to be used when compiling .lua
to .obj, to avoid name clash
]]

return {
    --src_lua/
    ['src_lua/NameRef.lua'] = 'NameRef',
    ['src_lua/UserInfo.lua'] = 'UserInfo',
    ['src_lua/flexi_CreateClass.lua'] = 'flexi_CreateClass',
    ['src_lua/flexi_DropClass.lua'] = 'flexi_DropClass',
    ['src_lua/flexi_SplitProperty.lua'] = 'flexi_SplitProperty',
    ['src_lua/ClassDef.lua'] = 'ClassDef',
    ['src_lua/flexi_AlterClass.lua'] = 'flexi_AlterClass',
    ['src_lua/flexi_CreateProperty.lua'] = 'flexi_CreateProperty',
    ['src_lua/flexi_DropProperty.lua'] = 'flexi_DropProperty',
    ['src_lua/flexi_StructuralMerge.lua'] = 'flexi_StructuralMerge',
    ['src_lua/DBContext.lua'] = 'DBContext',
    ['src_lua/PropertyDef.lua'] = 'PropertyDef',
    ['src_lua/flexi_AlterProperty.lua'] = 'flexi_AlterProperty',
    ['src_lua/flexi_DataBestIndex.lua'] = 'flexi_DataBestIndex',
    ['src_lua/flexi_MergeProperty.lua'] = 'flexi_MergeProperty',
    ['src_lua/flexi_StructuralSplit.lua'] = 'flexi_StructuralSplit',
    ['src_lua/EnumManager.lua'] = 'EnumManager',
    ['src_lua/QueryBuilder.lua'] = 'QueryBuilder',
    ['src_lua/flexi_Configure.lua'] = 'flexi_Configure',
    ['src_lua/flexi_DataFilter.lua'] = 'flexi_DataFilter',
    ['src_lua/flexi_ObjectToProp.lua'] = 'flexi_ObjectToProp',
    --['src_lua/index.lua'] = 'index',
    ['src_lua/JulianDate.lua'] = 'JulianDate',
    ['src_lua/Triggers.lua'] = 'Triggers',
    ['src_lua/flexi_ConvertCustomEAV.lua'] = 'flexi_ConvertCustomEAV',
    ['src_lua/flexi_DataUpdate.lua'] = 'flexi_DataUpdate',
    ['src_lua/flexi_PropToObject.lua'] = 'flexi_PropToObject',
    ['src_lua/DBObject.lua'] = 'DBObject',
    ['src_lua/Constants.lua'] = 'Constants',
    ['src_lua/AccessControl.lua'] = 'AccessControl',
    ['src_lua/Util.lua'] = 'Util',
    ['src_lua/DBValue.lua'] = 'DBValue',
    ['src_lua/ApiGlobalObject.lua'] = 'ApiGlobalObject',
    ['src_lua/ApiGlobalScope.lua'] = 'ApiGlobalScope',
    ['src_lua/DBProperty.lua'] = 'DBProperty',
    ['src_lua/ColMapping.lua'] = 'ColMapping',

    -- lib
    ['lib/lua-prettycjson/lib/resty/prettycjson.lua'] = 'prettycjson',
    ['lib/lua-schema/schema.lua'] = 'schema',
    ['lib/lua-date/date.lua'] = 'date',

    -- penlight
    ['lib/lua-penlight/lua/pl/Date.lua'] = 'pl.Date',
    ['lib/lua-penlight/lua/pl/Set.lua'] = 'pl.Set',
    ['lib/lua-penlight/lua/pl/comprehension.lua'] = 'pl.comprehension',
    ['lib/lua-penlight/lua/pl/func.lua'] = 'pl.func',
    ['lib/lua-penlight/lua/pl/lexer.lua'] = 'pl.lexer',
    ['lib/lua-penlight/lua/pl/pretty.lua'] = 'pl.pretty',
    ['lib/lua-penlight/lua/pl/stringx.lua'] = 'pl.stringx',
    ['lib/lua-penlight/lua/pl/types.lua'] = 'pl.types',
    ['lib/lua-penlight/lua/pl/List.lua'] = 'pl.List',
    ['lib/lua-penlight/lua/pl/app.lua'] = 'pl.app',
    ['lib/lua-penlight/lua/pl/config.lua'] = 'pl.config',
    ['lib/lua-penlight/lua/pl/import_into.lua'] = 'pl.import_into',
    ['lib/lua-penlight/lua/pl/luabalanced.lua'] = 'pl.luabalanced',
    ['lib/lua-penlight/lua/pl/seq.lua'] = 'pl.seq',
    ['lib/lua-penlight/lua/pl/tablex.lua'] = 'pl.tablex',
    ['lib/lua-penlight/lua/pl/url.lua'] = 'pl.url',
    ['lib/lua-penlight/lua/pl/Map.lua'] = 'pl.Map',
    ['lib/lua-penlight/lua/pl/array2d.lua'] = 'pl.array2d',
    ['lib/lua-penlight/lua/pl/data.lua'] = 'pl.data',
    ['lib/lua-penlight/lua/pl/init.lua'] = 'pl.init',
    ['lib/lua-penlight/lua/pl/operator.lua'] = 'pl.operator',
    ['lib/lua-penlight/lua/pl/sip.lua'] = 'pl.sip',
    ['lib/lua-penlight/lua/pl/template.lua'] = 'pl.template',
    ['lib/lua-penlight/lua/pl/utils.lua'] = 'pl.utils',
    ['lib/lua-penlight/lua/pl/MultiMap.lua'] = 'pl.MultiMap',
    ['lib/lua-penlight/lua/pl/class.lua'] = 'pl.class',
    ['lib/lua-penlight/lua/pl/dir.lua'] = 'pl.dir',
    ['lib/lua-penlight/lua/pl/input.lua'] = 'pl.input',
    ['lib/lua-penlight/lua/pl/path.lua'] = 'pl.path',
    ['lib/lua-penlight/lua/pl/strict.lua'] = 'pl.strict',
    ['lib/lua-penlight/lua/pl/test.lua'] = 'pl.test',
    ['lib/lua-penlight/lua/pl/xml.lua'] = 'pl.xml',
    ['lib/lua-penlight/lua/pl/OrderedMap.lua'] = 'pl.OrderedMap',
    ['lib/lua-penlight/lua/pl/compat.lua'] = 'pl.compat',
    ['lib/lua-penlight/lua/pl/file.lua'] = 'pl.file',
    ['lib/lua-penlight/lua/pl/lapp.lua'] = 'pl.lapp',
    ['lib/lua-penlight/lua/pl/permute.lua'] = 'pl.permute',
    ['lib/lua-penlight/lua/pl/stringio.lua'] = 'pl.stringio',
    ['lib/lua-penlight/lua/pl/text.lua'] = 'pl.text',

    -- sandbox
    ['lib/lua-sandbox/sandbox.lua'] = 'sandbox',

    -- metalua-parser
    ['lib/lua-metalua/metalua/grammar/generator.lua'] = 'metalua.grammar.generator',
    ['lib/lua-metalua/metalua/grammar/lexer.lua'] = 'metalua.grammar.lexer',
    ['lib/lua-metalua/metalua/compiler/parser.lua'] = 'metalua.compiler.parser',
    ['lib/lua-metalua/metalua/compiler/parser/common.lua'] = 'metalua.compiler.parser.common',
    ['lib/lua-metalua/metalua/compiler/parser/table.lua'] = 'metalua.compiler.parser.table',
    ['lib/lua-metalua/metalua/compiler/parser/ext.lua'] = 'metalua.compiler.parser.ext',
    ['lib/lua-metalua/metalua/compiler/parser/annot/generator.lua'] = 'metalua.compiler.parser.annot.generator',
    ['lib/lua-metalua/metalua/compiler/parser/annot/grammar.lua'] = 'metalua.compiler.parser.annot.grammar',
    ['lib/lua-metalua/metalua/compiler/parser/stat.lua'] = 'metalua.compiler.parser.stat',
    ['lib/lua-metalua/metalua/compiler/parser/misc.lua'] = 'metalua.compiler.parser.misc',
    ['lib/lua-metalua/metalua/compiler/parser/lexer.lua'] = 'metalua.compiler.parser.lexer',
    ['lib/lua-metalua/metalua/compiler/parser/meta.lua'] = 'metalua.compiler.parser.meta',
    ['lib/lua-metalua/metalua/compiler/parser/expr.lua'] = 'metalua.compiler.parser.expr',
    ['lib/lua-metalua/metalua/compiler.lua'] = 'metalua.compiler',
    ['lib/lua-metalua/metalua/pprint.lua'] = 'metalua.pprint',
    ['lib/lua-metalua/checks.lua'] = 'checks',
}