---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-06-12 6:25 PM
---

--[[
List of all Lua files (including 3rd parties) with paths relative to the project
Optional value is an alternative module name, to be used when compiling .lua
to .obj, to avoid name clash
]]

return {
    --src_lua/
    ['NameRef'] = 'src_lua/NameRef.lua',
    ['UserInfo'] = 'src_lua/UserInfo.lua',
    ['flexi_CreateClass'] = 'src_lua/flexi_CreateClass.lua',
    ['flexi_DropClass'] = 'src_lua/flexi_DropClass.lua',
    ['flexi_SplitProperty'] = 'src_lua/flexi_SplitProperty.lua',
    ['ClassDef'] = 'src_lua/ClassDef.lua',
    ['flexi_AlterClass'] = 'src_lua/flexi_AlterClass.lua',
    ['flexi_CreateProperty'] = 'src_lua/flexi_CreateProperty.lua',
    ['flexi_DropProperty'] = 'src_lua/flexi_DropProperty.lua',
    ['flexi_StructuralMerge'] = 'src_lua/flexi_StructuralMerge.lua',
    ['DBContext'] = 'src_lua/DBContext.lua',
    ['PropertyDef'] = 'src_lua/PropertyDef.lua',
    ['flexi_AlterProperty'] = 'src_lua/flexi_AlterProperty.lua',
    ['flexi_DataBestIndex'] = 'src_lua/flexi_DataBestIndex.lua',
    ['flexi_MergeProperty'] = 'src_lua/flexi_MergeProperty.lua',
    ['flexi_StructuralSplit'] = 'src_lua/flexi_StructuralSplit.lua',
    ['RefDataManager'] = 'src_lua/RefDataManager.lua',
    ['QueryBuilder'] = 'src_lua/QueryBuilder.lua',
    ['flexi_Configure'] = 'src_lua/flexi_Configure.lua',
    ['flexi_DataFilter'] = 'src_lua/flexi_DataFilter.lua',
    ['flexi_ObjectToProp'] = 'src_lua/flexi_ObjectToProp.lua',
    ['JulianDate'] = 'src_lua/JulianDate.lua',
    ['Triggers'] = 'src_lua/Triggers.lua',
    ['flexi_ConvertCustomEAV'] = 'src_lua/flexi_ConvertCustomEAV.lua',
    ['flexi_DataUpdate'] = 'src_lua/flexi_DataUpdate.lua',
    ['flexi_PropToObject'] = 'src_lua/flexi_PropToObject.lua',
    ['DBObject'] = 'src_lua/DBObject.lua',
    ['Constants'] = 'src_lua/Constants.lua',
    ['AccessControl'] = 'src_lua/AccessControl.lua',
    ['Util'] = 'src_lua/Util.lua',
    ['DBValue'] = 'src_lua/DBValue.lua',
    ['ApiGlobalObject'] = 'src_lua/ApiGlobalObject.lua',
    ['ApiGlobalScope'] = 'src_lua/ApiGlobalScope.lua',
    ['DBProperty'] = 'src_lua/DBProperty.lua',
    ['ColMapping'] = 'src_lua/ColMapping.lua',
    ['flexi_rel_vtable'] = 'src_lua/flexi_rel_vtable.lua',
    ['flexi_data_vtable'] = 'src_lua/flexi_data_vtable.lua',
    ['SqliteTable'] = 'src_lua/SqliteTable.lua',
    ['events'] = 'src_lua/EventEmitter.lua',

    -- sql
    ['sql.dbschema'] = 'sql/dbschema.sql',
    ['sql.init_default_data'] = 'sql/init_default_data.sql',

    -- lib
    ['prettycjson'] = 'lib/lua-prettycjson/lib/resty/prettycjson.lua',
    ['schema'] = 'lib/lua-schema/schema.lua',
    ['date'] = 'lib/lua-date/src/date.lua',
    --['date'] = 'lib/lua-date/date.lua',
    ['debugger'] = 'lib/debugger-lua/debugger.lua',

    -- penlight
    ['pl.Date'] = 'lib/lua-penlight/lua/pl/Date.lua',
    ['pl.Set'] = 'lib/lua-penlight/lua/pl/Set.lua',
    ['pl.comprehension'] = 'lib/lua-penlight/lua/pl/comprehension.lua',
    ['pl.func'] = 'lib/lua-penlight/lua/pl/func.lua',
    ['pl.lexer'] = 'lib/lua-penlight/lua/pl/lexer.lua',
    ['pl.pretty'] = 'lib/lua-penlight/lua/pl/pretty.lua',
    ['pl.stringx'] = 'lib/lua-penlight/lua/pl/stringx.lua',
    ['pl.types'] = 'lib/lua-penlight/lua/pl/types.lua',
    ['pl.List'] = 'lib/lua-penlight/lua/pl/List.lua',
    ['pl.app'] = 'lib/lua-penlight/lua/pl/app.lua',
    ['pl.config'] = 'lib/lua-penlight/lua/pl/config.lua',
    ['pl.import_into'] = 'lib/lua-penlight/lua/pl/import_into.lua',
    ['pl.luabalanced'] = 'lib/lua-penlight/lua/pl/luabalanced.lua',
    ['pl.seq'] = 'lib/lua-penlight/lua/pl/seq.lua',
    ['pl.tablex'] = 'lib/lua-penlight/lua/pl/tablex.lua',
    ['pl.url'] = 'lib/lua-penlight/lua/pl/url.lua',
    ['pl.Map'] = 'lib/lua-penlight/lua/pl/Map.lua',
    ['pl.array2d'] = 'lib/lua-penlight/lua/pl/array2d.lua',
    ['pl.data'] = 'lib/lua-penlight/lua/pl/data.lua',
    ['pl.init'] = 'lib/lua-penlight/lua/pl/init.lua',
    ['pl.operator'] = 'lib/lua-penlight/lua/pl/operator.lua',
    ['pl.sip'] = 'lib/lua-penlight/lua/pl/sip.lua',
    ['pl.template'] = 'lib/lua-penlight/lua/pl/template.lua',
    ['pl.utils'] = 'lib/lua-penlight/lua/pl/utils.lua',
    ['pl.MultiMap'] = 'lib/lua-penlight/lua/pl/MultiMap.lua',
    ['pl.class'] = 'lib/lua-penlight/lua/pl/class.lua',
    ['pl.dir'] = 'lib/lua-penlight/lua/pl/dir.lua',
    ['pl.input'] = 'lib/lua-penlight/lua/pl/input.lua',
    ['pl.path'] = 'lib/lua-penlight/lua/pl/path.lua',
    ['pl.strict'] = 'lib/lua-penlight/lua/pl/strict.lua',
    ['pl.test'] = 'lib/lua-penlight/lua/pl/test.lua',
    ['pl.xml'] = 'lib/lua-penlight/lua/pl/xml.lua',
    ['pl.OrderedMap'] = 'lib/lua-penlight/lua/pl/OrderedMap.lua',
    ['pl.compat'] = 'lib/lua-penlight/lua/pl/compat.lua',
    ['pl.file'] = 'lib/lua-penlight/lua/pl/file.lua',
    ['pl.lapp'] = 'lib/lua-penlight/lua/pl/lapp.lua',
    ['pl.permute'] = 'lib/lua-penlight/lua/pl/permute.lua',
    ['pl.stringio'] = 'lib/lua-penlight/lua/pl/stringio.lua',
    ['pl.text'] = 'lib/lua-penlight/lua/pl/text.lua',

    -- sandbox
    ['sandbox'] = 'lib/lua-sandbox/sandbox.lua',

    -- metalua-parser
    ['metalua.grammar.generator'] = 'lib/lua-metalua/metalua/grammar/generator.lua',
    ['metalua.grammar.lexer'] = 'lib/lua-metalua/metalua/grammar/lexer.lua',
    ['metalua.compiler.parser'] = 'lib/lua-metalua/metalua/compiler/parser.lua',
    ['metalua.compiler.parser.common'] = 'lib/lua-metalua/metalua/compiler/parser/common.lua',
    ['metalua.compiler.parser.table'] = 'lib/lua-metalua/metalua/compiler/parser/table.lua',
    ['metalua.compiler.parser.ext'] = 'lib/lua-metalua/metalua/compiler/parser/ext.lua',
    ['metalua.compiler.parser.annot.generator'] = 'lib/lua-metalua/metalua/compiler/parser/annot/generator.lua',
    ['metalua.compiler.parser.annot.grammar'] = 'lib/lua-metalua/metalua/compiler/parser/annot/grammar.lua',
    ['metalua.compiler.parser.stat'] = 'lib/lua-metalua/metalua/compiler/parser/stat.lua',
    ['metalua.compiler.parser.misc'] = 'lib/lua-metalua/metalua/compiler/parser/misc.lua',
    ['metalua.compiler.parser.lexer'] = 'lib/lua-metalua/metalua/compiler/parser/lexer.lua',
    ['metalua.compiler.parser.meta'] = 'lib/lua-metalua/metalua/compiler/parser/meta.lua',
    ['metalua.compiler.parser.expr'] = 'lib/lua-metalua/metalua/compiler/parser/expr.lua',
    ['metalua.compiler'] = 'lib/lua-metalua/metalua/compiler.lua',
    ['metalua.pprint'] = 'lib/lua-metalua/metalua/pprint.lua',
    ['checks'] = 'lib/lua-metalua/checks.lua',
}
