---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slanska.
--- DateTime: 2018-03-11 7:01 PM
---

-- Merges 2 or more existing objects, so that one object would be left in database
-- Values are taken from the object which was updated most recently
-- Normally, all participating objects should belong to the same class, but it is allowed for
-- objects to belong to different classes
-- Updates all references
-- After merging, objects found by sourceFilter get deleted
-- This function is typically used to get rid of accidental duplicates (when, e.g. country, city or person names are mispelled and thus
-- are defied in multiple records)
---@param self DBContext
---@param targetFilter string @comment Valid Lua expression which should return one object only
---@param sourceFilter string @comment Valid Lua expression which may return more than one object
local function MergeObjects(self, targetFilter, sourceFilter)

end

return MergeObjects