---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by slan_ska.
--- DateTime: 2018-10-17 7:14 PM
---

--[[
These are few "complex" callback methods needed by flexi_rel SQLite
virtual table. Refer to src/flexi/flexi_rel.cpp for more details
]]


---@param DBContext DBContext
---@param dbName string @comment main, temp...
---@param tableName string @comment new flexi_rel table name
---@param className string @comment class to be used as base
---@param propName string @comment reference property in className
---@param col1Name string @comment alias for column1 ("ObjectID" or "from")
---@param col2Name string @comment alias for column2 ("Value" or "to")
---@return bool, string @comment true if success, and false and error message if failed
local function create_connect(DBContext, dbName, tableName, className, propName,
                              col1Name, col2Name)
    -- check permission to create new tables
    -- get class
    -- get property
    -- ensure that this is reference property
    -- get "to" class
    --
end

local function best_index()

end

local function filter()

end

local function update()

end

return {
    create_connect = create_connect,
    best_index = best_index,
    filter = filter,
    update = update,
}